# -*- coding: utf-8 -*-
"""RegresiónLogistica.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RBOxaDcKVVA-DD2WD-ipzwerwoAWpetn
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
import matplotlib.pyplot as plt

##cargando la base de datos..

from google.colab import files

from google.colab import drive 

drive.mount('/content/drive')

import pandas as pd 
df = pd.read_excel("/content/drive/MyDrive/analisis /B.xlsx")
df.shape

##estimando el modelo de regresión logistica 
x=df[['edad','anuales']]
y=df[['altos']]

#dividir data

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=0)

#instanciamos

log_regression=LogisticRegression()

#ajustar modelo 

log_regression.fit(x_train,y_train)

#usar modelo para hacer predicciones del testing 

y_pred=log_regression.predict(x_test)
y_pred

#el 0 indica salario alto y el 0 salario bajo

#diagnosticos del modelo para validar 
cnf_matrix=metrics.confusion_matrix(y_test,y_pred)
cnf_matrix

#diagonal pricipal son los bien error 0 hay 6 1 y 4 0

print("Accuracy:",metrics.accuracy_score(y_test,y_pred))

#porcentaje

log_regression.predict([[25,38000]])